import { translateText } from './i18n'
import { useEffect, useState } from 'react'
import { loadDemo, loadEkt, loadAnomalies, calculate, uploadFile, uploadWorkbook, getOutliers } from './api'
import { number as money } from './ui'

export function Imports({ onToast, onRefresh }: { onToast: (message: string) => void; onRefresh: () => Promise<void> }) {
  const [busy, setBusy] = useState(false)
  const [report, setReport] = useState('')
  const [error, setError] = useState(false)
  const run = async (action: () => Promise<string>) => { setBusy(true); setError(false); setReport(''); try { const message = await action(); setReport(message); await onRefresh() } catch (e) { setError(true); setReport(e instanceof Error ? e.message : 'Ошибка загрузки') } finally { setBusy(false) } }
  const upload = (key: string, file?: File) => { if (!file) return; void run(async () => { const result = key === 'workbook' ? await uploadWorkbook(file) : await uploadFile(key, file); return [`${file.name}: рассчитано рекомендаций — ${result.recommendations}`, ...result.errors, ...result.warnings].join('\n') }) }
  return <section className="content-card"><div className="card-header"><div><h2>{translateText("Загрузка данных")}</h2><p>{translateText("CSV и Excel · русские и английские заголовки")}</p></div></div><div className="panel-body"><p>{translateText("Загрузка заменяет соответствующий набор и пересчитывает рекомендации.")}</p>{report && <p className={error ? 'error report' : 'report'} role={error ? 'alert' : 'status'}>{report}</p>}<div className="import-grid">{[['workbook', 'Полная книга Excel', 'Продажи, остатки, товары в пути, дефициты и поставщики'], ['sales', 'История продаж', 'Дневные продажи по товарам и складам'], ['stock', 'Остатки', 'Текущий запас на складах'], ['transit', 'Товары в пути', 'Количество и ожидаемые даты'], ['stockouts', 'Периоды дефицита', 'Начало и конец отсутствия товара'], ['suppliers', 'Поставщики', 'Сроки, минимальные партии и упаковки']].map(([key, title, hint]) => <label className="dropzone" key={key}><strong>{translateText(title)}</strong><span>{translateText(hint)}</span><input aria-label={translateText(title)} type="file" disabled={busy} accept={key === 'workbook' ? '.xls,.xlsx' : '.csv,.xls,.xlsx'} onChange={e => { upload(key, e.target.files?.[0]); e.target.value = '' }}/></label>)}</div><details className="processing-note"><summary>{translateText("Демонстрационные наборы")}</summary><p>{translateText("Выбор заменит текущие данные. Используйте для проверки приложения.")}</p><div className="actions"><button className="button subtle" disabled={busy} onClick={() => run(async () => { await loadDemo(); await calculate(); onToast('Демонстрационные данные загружены'); return 'Базовый сценарий загружен.' })}>{translateText("Базовый сценарий")}</button><button className="button subtle" disabled={busy} onClick={() => run(async () => { await loadEkt(); return 'Набор ekt.kz загружен.' })}>{translateText("Набор ekt.kz")}</button><button className="button subtle" disabled={busy} onClick={() => run(async () => { await loadAnomalies(); return 'Набор аномалий загружен.' })}>{translateText("Сценарий аномалий")}</button></div></details>{busy && <p role="status">{translateText("Загружаем и пересчитываем…")}</p>}</div></section>
}

type Outlier = { date: string; sku: string; warehouse: string; customer_id: string; quantity: number; typical_quantity: number; used_in_forecast: boolean; reason: string }

export function Anomalies() {
  const [items, setItems] = useState<Outlier[]>([])
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(true)
  useEffect(() => { getOutliers().then(result => setItems(result.outliers as Outlier[])).catch(error => setError(error.message)).finally(() => setLoading(false)) }, [])
  return <section className="content-card anomaly-page">{error && <p className="error" role="alert">{error}</p>}<div className="card-header"><div><p className="eyebrow">{translateText("ПРОВЕРКА ДАННЫХ")}</p><h3>{translateText("Обнаруженные аномалии")}<span>{items.length}</span></h3><p className="subcopy">{translateText("Крупные разовые продажи исключаются из регулярного спроса и сохраняются для проверки.")}</p></div></div><div className="table-wrap"><table><thead><tr><th>{translateText("Дата")}</th><th>{translateText("SKU / склад")}</th><th>{translateText("Клиент")}</th><th>{translateText("Количество")}</th><th>{translateText("Обычно")}</th><th>{translateText("В прогнозе")}</th><th>{translateText("Причина")}</th></tr></thead><tbody>{items.map((item, index) => <tr key={index}><td data-label={translateText("Дата")}>{item.date}</td><td data-label={translateText("SKU / склад")}><strong>{item.sku}</strong><span className="cell-muted">{item.warehouse}</span></td><td data-label={translateText("Клиент")}>{item.customer_id}</td><td data-label={translateText("Количество")}><strong className="danger-text">{money(item.quantity)}</strong></td><td data-label={translateText("Обычно")}>{money(item.typical_quantity)}</td><td data-label={translateText("В прогнозе")}><span className="reason-pill">{item.used_in_forecast ? 'Включено' : 'Исключено'}</span></td><td data-label={translateText("Причина")}><span className="reason-pill">{item.reason}</span></td></tr>)}</tbody></table>{!items.length && <div className="empty">{loading ? 'Загружаем исключения…' : error ? 'Данные недоступны.' : 'Аномалий не обнаружено.'}</div>}</div></section>
}
