import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react'

export type Locale = 'ru' | 'en' | 'kk'
export type DateFormat = 'locale' | 'iso'
export type NumberFormat = 'locale' | 'plain'

export interface UserSettings {
  dateFormat: DateFormat
  numberFormat: NumberFormat
  compactMode: boolean
  autoOpenDraft: boolean
}

const LOCALE_STORAGE_KEY = 'stockpilot.locale'
const SETTINGS_STORAGE_KEY = 'stockpilot.settings'
const defaultSettings: UserSettings = { dateFormat: 'locale', numberFormat: 'locale', compactMode: false, autoOpenDraft: true }

const translations: Record<Locale, Record<string, string>> = {
  ru: {
    overview: 'Обзор', editor: 'Редактор данных', imports: 'Загрузка данных', anomalies: 'Аномалии', settings: 'Настройки',
    controlRoom: 'ЦЕНТР УПРАВЛЕНИЯ', engineOnline: 'Движок онлайн', version: 'v1.2 · ekt.kz + аномалии',
    purchasingEyebrow: 'ЗАКУПКИ / УПРАВЛЕНИЕ СКЛАДОМ', overviewTitle: 'Кабина пополнения', liveData: '● Актуальные данные · {date}', syntheticDemo: '↻ Синтетическое демо', ektDataset: '⚡️ Данные ekt.kz (Казахстан)', anomaliesStress: '💥 Аномалии (стресс-тест)',
    needReplenishment: 'Нужно пополнить', skuWarehousePairs: 'пары SKU / склад', criticalRisk: 'Критический риск', stockoutBeforeArrival: 'дефицит до поставки', unitsToOrder: 'Единиц к заказу', afterPackageRounding: 'с учётом упаковки', orderBudget: 'Бюджет заказа', estimatedProcurementCost: 'оценочная стоимость закупки', suppliersInvolved: 'Поставщики', readyToReview: 'готовы к проверке', anomaliesRemoved: 'Аномалии исключены', preservedForAudit: 'сохранены для аудита', lostDemandAdded: 'Упущенный спрос', stockoutCorrection: 'коррекция дефицита',
    whatShouldWeOrder: 'Что нужно заказать', rightNow: 'прямо сейчас?', recommendationsIntro: 'Рекомендации учитывают спрос, остатки, товары в пути и ограничения поставщика — у каждого числа есть объяснение.', actionQueue: 'ОЧЕРЕДЬ ДЕЙСТВИЙ', recommendedOrders: 'Рекомендуемые заказы', searchSku: 'Поиск SKU или товара…', allWarehouses: 'Все склады', allSuppliers: 'Все поставщики', allCategories: 'Все категории', allUrgency: 'Любая срочность', sortByUrgency: 'Сначала срочные', largestOrder: 'Самый большой заказ', lowestCover: 'Наименьший запас', noRecommendations: 'Нет рекомендаций по этим фильтрам.',
    urgency: 'Срочность', skuProduct: 'SKU / товар', supplierColumn: 'Поставщик', stockPosition: 'Остаток', demandLeadTime: 'Спрос / срок', orderBudgetColumn: 'Заказ и бюджет', cover: 'Покрытие', action: 'Действие', currentStock: 'текущий остаток', inTransit: 'в пути', dayLead: 'дн. поставки', orderStatus: 'статус', groupedBySupplier: 'Группировка по поставщику', reviewBeforeApproval: 'Проверьте перед утверждением',
    supplierSku: '{count} SKU · срок {days} дн.',
    supplier: 'Поставщик', leadTime: 'Срок поставки', stockIncoming: 'Остаток + в пути', trend: 'Тренд', recentDailyDemand: 'Средний дневной спрос', demandVolatility: 'Изменчивость спроса', seasonality: 'Сезонность', detected: 'Обнаружена', notDetected: 'Не обнаружена', auditAdjustments: 'Корректировки аудита', anomaliesLostDemand: '{anomalies} аномалий · {demand} упущенного спроса', demandSignal: 'Сигнал спроса', weeklyAverages: 'недельные средние · последние 90 дн. + прогноз', actual: 'факт', adjusted: 'скорректированный', forecast: 'прогноз', stockout: 'дефицит', anomaly: 'аномалия', calculationTrace: 'РАСЧЁТ', forecastDuringLeadTime: 'Прогноз на срок поставки', safetyStock: '+ Страховой запас', currentStockIncoming: '− Текущий остаток / в пути', recommendedQuantity: 'Рекомендуемое количество', whyThisNumber: 'Почему это число?', finalQuantity: 'Итоговое количество', saveAdjustment: 'Сохранить правку', approved: '✓ Утверждено', approveOrder: 'Утвердить заказ', approvalRequired: 'Перед действием поставщика требуется утверждение.',
    dataFoundation: 'ОСНОВА ДАННЫХ', bringSignals: 'Объедините свои сигналы.', uploadDescription: 'Загрузите операционные данные или полный Excel-файл ekt.kz. Поддерживаются русские и английские заголовки.', loadSynthetic: 'Загрузить демо', loadEkt: 'Загрузить данные ekt.kz (ТОО «Электрокомплект»)', loadExtreme: 'Загрузить датасет экстремальных аномалий', uploadWorkbook: 'Загрузить полный Excel-файл ekt.kz (5 листов)', uploadWorkbookHint: 'Автоматически распознаёт продажи, остатки, товары в пути, поставщиков и дефициты с нормализацией заголовков', browseFile: 'Перетащите файл или выберите его', salesHistory: 'История продаж', currentStockImport: 'Текущие остатки', goodsInTransit: 'Товары в пути', stockoutWindows: 'Периоды дефицита', supplierCatalog: 'Каталог поставщиков', dailyTransactions: 'операции по дням · CSV / XLSX', inventoryByWarehouse: 'остатки SKU по складам', expectedArrivals: 'ожидаемые поставки', lostDemandCorrection: 'коррекция упущенного спроса', leadMoqPackage: 'сроки · MOQ · упаковка', safeOperations: 'Безопасная работа', privacyDescription: 'Идентификаторы клиентов используются только как обезличенные ссылки. PII не требуется, заказы не отправляются автоматически.',
    auditTrail: 'ЖУРНАЛ АУДИТА', detectedAnomalies: 'Обнаруженные аномалии', excludedExplanation: 'Крупные разовые операции исключены из обычного спроса, но не удалены.', date: 'Дата', skuWarehouse: 'SKU / склад', customer: 'Клиент', quantity: 'Количество', typical: 'Обычно', forecastUse: 'В прогнозе', reason: 'Причина', included: 'Включено', excluded: 'Исключено', noAnomalies: 'Аномалий пока нет. Запустите демо, чтобы заполнить журнал аудита.',
    dataWorkspace: 'РАБОЧАЯ ОБЛАСТЬ ДАННЫХ', dataEditorTitle: 'Редактор данных', dataEditorDescription: 'Создавайте товары, поставщиков и операции прямо в StockPilot. Черновик сохраняется автоматически.', draftRestored: '↩ Черновик восстановлен', savedToSqlite: '● Данные сохраняются в SQLite', records: 'Записи', find: 'Найти…', newRow: '＋ Новая строка', actions: 'Действия', edit: 'Изменить', delete: 'Удалить', noRecords: 'Пока нет записей. Создайте первую строку.', recordsCount: '{from}–{to} из {total}', zeroRecords: '0 записей', newRecord: 'НОВАЯ ЗАПИСЬ', editRecord: 'РЕДАКТИРОВАНИЕ', addRow: 'Добавить строку', editRow: 'Изменить строку', saveRow: 'Сохранить строку', saveChanges: 'Сохранить изменения', saving: 'Сохраняем…', editorHint: 'Последнее состояние формы автоматически сохраняется как черновик каждые несколько секунд.', required: 'обязательно', yes: 'Да', no: 'Нет',
    products: 'Товары', productsDescription: 'Справочник SKU для продаж и поставок', sales: 'Продажи', salesDescription: 'Фактические продажи по дням', stock: 'Остатки', stockDescription: 'Текущий запас по складам', transit: 'В пути', transitDescription: 'Ожидаемые поставки', stockouts: 'Дефициты', stockoutsDescription: 'Периоды нулевого остатка', suppliers: 'Поставщики', suppliersDescription: 'Срок поставки, MOQ и упаковка', productName: 'Название товара', category: 'Категория', price: 'Цена', active: 'Активен', customerId: 'Клиент', warehouse: 'Склад', start: 'Начало', end: 'Конец', arrivalDate: 'Дата поставки', supplierId: 'ID поставщика', supplierName: 'Поставщик', leadTimeDays: 'Срок поставки, дней', moq: 'MOQ', packageSize: 'Упаковка', purchasePrice: 'Цена закупки', minimumOrderValue: 'Мин. сумма заказа',
    settingsTitle: 'Настройки', settingsDescription: 'Настройте StockPilot под свой рабочий процесс. Изменения сохраняются на этом устройстве.', generalSettings: 'Основные настройки', language: 'Язык интерфейса', languageDescription: 'Выберите язык всех элементов приложения.', dateFormat: 'Формат даты', dateFormatDescription: 'Выберите привычное отображение дат.', localDate: 'Локальный формат', isoDate: 'ISO (2026-09-23)', numberFormat: 'Формат чисел', numberFormatDescription: 'Локальные разделители или простой формат.', localeNumbers: 'Локальный', plainNumbers: 'Без разделителей', compactMode: 'Компактные таблицы', compactModeDescription: 'Уменьшить отступы в таблицах для большего количества строк.', autoOpenDraft: 'Открывать черновик автоматически', autoOpenDraftDescription: 'После входа сразу открывать незавершённую запись редактора.', resetSettings: 'Сбросить настройки', settingsSaved: 'Настройки сохранены', settingsReset: 'Настройки сброшены', languageRussian: 'Русский', languageEnglish: 'English', languageKazakh: 'Қазақша',
    demoLoaded: 'Демо-сценарий загружен и пересчитан', ektLoaded: '⚡️ Данные ТОО «Электрокомплект» загружены и рассчитаны!', anomaliesLoaded: '💥 Датасет аномалий загружен! Выявлено {outliers} аномалий, пересчитано {recommendations} заказов!', couldNotLoad: 'Не удалось загрузить данные', couldNotLoadRecommendations: 'Не удалось загрузить рекомендации', analyticsError: 'Не удалось загрузить аналитику', orderApproved: 'Заказ утверждён', quantityAdjusted: 'Количество скорректировано', workbookLoaded: 'Excel-файл загружен: рассчитано рекомендаций — {count}', demoDatasetLoaded: 'Демо-датасет загружен', draftUnavailable: 'Черновик пока недоступен', changesSaved: 'Изменения сохранены, рекомендации пересчитаны', couldNotSave: 'Не удалось сохранить строку', rowDeleted: 'Строка удалена', couldNotDelete: 'Не удалось удалить строку', confirmDelete: 'Удалить эту строку?', uploadFailed: 'Не удалось загрузить файл', workbookUploadFailed: 'Не удалось загрузить Excel-файл',
  },
  en: {
    overview: 'Overview', editor: 'Data editor', imports: 'Data intake', anomalies: 'Anomalies', settings: 'Settings',
    controlRoom: 'CONTROL ROOM', engineOnline: 'Engine online', version: 'v1.2 · ekt.kz + anomalies', purchasingEyebrow: 'PURCHASING / WAREHOUSE CONTROL', overviewTitle: 'Replenishment Cockpit', liveData: '● Live data · {date}', syntheticDemo: '↻ Synthetic demo', ektDataset: '⚡️ ekt.kz Dataset (Kazakhstan)', anomaliesStress: '💥 Anomalies (Stress Test)',
    needReplenishment: 'Need replenishment', skuWarehousePairs: 'SKU / warehouse pairs', criticalRisk: 'Critical risk', stockoutBeforeArrival: 'stockout before arrival', unitsToOrder: 'Units to order', afterPackageRounding: 'after package rounding', orderBudget: 'Order budget', estimatedProcurementCost: 'estimated procurement cost', suppliersInvolved: 'Suppliers involved', readyToReview: 'ready to review', anomaliesRemoved: 'Anomalies removed', preservedForAudit: 'preserved for audit', lostDemandAdded: 'Lost demand added', stockoutCorrection: 'stockout correction', whatShouldWeOrder: 'What should we order', rightNow: 'right now?', recommendationsIntro: 'Recommendations balance demand, stock, incoming goods and supplier constraints — with a reason for every number.', actionQueue: 'ACTION QUEUE', recommendedOrders: 'Recommended orders', searchSku: 'Search SKU or product…', allWarehouses: 'All warehouses', allSuppliers: 'All suppliers', allCategories: 'All categories', allUrgency: 'All urgency', sortByUrgency: 'Sort by urgency', largestOrder: 'Largest order', lowestCover: 'Lowest cover', noRecommendations: 'No recommendations match these filters.', urgency: 'Urgency', skuProduct: 'SKU / product', supplier: 'Supplier', stockPosition: 'Stock position', demandLeadTime: 'Demand / lead time', orderBudgetColumn: 'Order & budget', cover: 'Cover', action: 'Action', currentStock: 'current stock', inTransit: 'in transit', dayLead: 'day lead', orderStatus: 'status', groupedBySupplier: 'Grouped by supplier', reviewBeforeApproval: 'Review before approval', supplierSku: '{count} SKU · {days} day lead', leadTime: 'Lead time', stockIncoming: 'Stock + incoming', trend: 'Trend', recentDailyDemand: 'Recent daily demand', demandVolatility: 'Demand volatility', seasonality: 'Seasonality', detected: 'Detected', notDetected: 'Not detected', auditAdjustments: 'Audit adjustments', anomaliesLostDemand: '{anomalies} anomalies · {demand} lost demand', demandSignal: 'Demand signal', weeklyAverages: 'weekly averages · recent 90d + forecast', actual: 'actual', adjusted: 'adjusted', forecast: 'forecast', stockout: 'stockout', anomaly: 'anomaly', calculationTrace: 'CALCULATION TRACE', forecastDuringLeadTime: 'Forecast during lead time', safetyStock: '+ Safety stock', currentStockIncoming: '− Current stock / incoming', recommendedQuantity: 'Recommended quantity', whyThisNumber: 'Why this number?', finalQuantity: 'Final quantity', saveAdjustment: 'Save adjustment', approved: '✓ Approved', approveOrder: 'Approve order', approvalRequired: 'Approval is required before any supplier action.',
    dataFoundation: 'DATA FOUNDATION', bringSignals: 'Bring your signals together.', uploadDescription: 'Upload clean operational data or full ekt.kz multi-sheet workbook. Supports both Russian and English headers.', loadSynthetic: 'Load synthetic demo', loadEkt: 'Load ekt.kz Dataset (ТОО «Электрокомплект»)', loadExtreme: 'Load Extreme Anomalies Dataset', uploadWorkbook: 'Upload full ekt.kz Excel workbook (5 sheets)', uploadWorkbookHint: 'Automatically parses sales, stock, transit, suppliers, and stockouts with column alias normalization', browseFile: 'Drop file or browse', salesHistory: 'Sales history', currentStockImport: 'Current stock', goodsInTransit: 'Goods in transit', stockoutWindows: 'Stockout windows', supplierCatalog: 'Supplier catalog', dailyTransactions: 'daily transactions · CSV / XLSX', inventoryByWarehouse: 'SKU inventory by warehouse', expectedArrivals: 'expected arrivals', lostDemandCorrection: 'lost demand correction', leadMoqPackage: 'lead times · MOQ · packages', safeOperations: 'Designed for safe operations', privacyDescription: 'Customer IDs are treated as anonymized references only. No PII is required, and no order is sent automatically.',
    auditTrail: 'AUDIT TRAIL', detectedAnomalies: 'Detected anomalies', excludedExplanation: 'Large one-off transactions are excluded from regular demand, never deleted.', date: 'Date', skuWarehouse: 'SKU / warehouse', customer: 'Customer', quantity: 'Quantity', typical: 'Typical', forecastUse: 'Forecast use', reason: 'Reason', included: 'Included', excluded: 'Excluded', noAnomalies: 'No anomalies detected yet. Run the demo scenario to populate the audit trail.',
    dataWorkspace: 'DATA WORKSPACE', dataEditorTitle: 'Data editor', dataEditorDescription: 'Create products, suppliers and operations directly in StockPilot. Drafts are saved automatically.', draftRestored: '↩ Draft restored', savedToSqlite: '● Data is saved to SQLite', records: 'Records', find: 'Find…', newRow: '＋ New row', actions: 'Actions', edit: 'Edit', delete: 'Delete', noRecords: 'No records yet. Create the first row.', recordsCount: '{from}–{to} of {total}', zeroRecords: '0 records', newRecord: 'NEW RECORD', editRecord: 'EDIT RECORD', addRow: 'Add row', editRow: 'Edit row', saveRow: 'Save row', saveChanges: 'Save changes', saving: 'Saving…', editorHint: 'The latest form state is automatically saved as a draft every few seconds.', required: 'required', yes: 'Yes', no: 'No', products: 'Products', productsDescription: 'SKU catalog for sales and replenishment', sales: 'Sales', salesDescription: 'Actual daily sales', stock: 'Stock', stockDescription: 'Current stock by warehouse', transit: 'In transit', transitDescription: 'Expected deliveries', stockouts: 'Stockouts', stockoutsDescription: 'Zero-stock periods', suppliers: 'Suppliers', suppliersDescription: 'Lead time, MOQ and packaging', productName: 'Product name', category: 'Category', price: 'Price', active: 'Active', customerId: 'Customer', warehouse: 'Warehouse', start: 'Start', end: 'End', arrivalDate: 'Arrival date', supplierId: 'Supplier ID', supplierName: 'Supplier', leadTimeDays: 'Lead time, days', moq: 'MOQ', packageSize: 'Package', purchasePrice: 'Purchase price', minimumOrderValue: 'Minimum order value',
    settingsTitle: 'Settings', settingsDescription: 'Configure StockPilot for your workflow. Changes are saved on this device.', generalSettings: 'General settings', language: 'Interface language', languageDescription: 'Choose the language for all application elements.', dateFormat: 'Date format', dateFormatDescription: 'Choose the date display you are used to.', localDate: 'Local format', isoDate: 'ISO (2026-09-23)', numberFormat: 'Number format', numberFormatDescription: 'Localized separators or a plain format.', localeNumbers: 'Localized', plainNumbers: 'No separators', compactMode: 'Compact tables', compactModeDescription: 'Reduce table spacing to show more rows.', autoOpenDraft: 'Open draft automatically', autoOpenDraftDescription: 'Open an unfinished editor record immediately after sign-in.', resetSettings: 'Reset settings', settingsSaved: 'Settings saved', settingsReset: 'Settings reset', languageRussian: 'Русский', languageEnglish: 'English', languageKazakh: 'Қазақша',
    demoLoaded: 'Demo scenario loaded and recalculated', ektLoaded: '⚡️ ТОО «Электрокомплект» data loaded & calculated!', anomaliesLoaded: '💥 Anomaly dataset loaded! Found {outliers} anomalies, recalculated {recommendations} orders!', couldNotLoad: 'Could not load data', couldNotLoadRecommendations: 'Could not load recommendations', analyticsError: 'Could not load SKU analytics', orderApproved: 'Order approved', quantityAdjusted: 'Quantity adjusted', workbookLoaded: 'Excel workbook loaded: {count} recommendations calculated', demoDatasetLoaded: 'Demo dataset loaded', draftUnavailable: 'Draft is not available yet', changesSaved: 'Changes saved, recommendations recalculated', couldNotSave: 'Could not save the row', rowDeleted: 'Row deleted', couldNotDelete: 'Could not delete the row', confirmDelete: 'Delete this row?', uploadFailed: 'Upload failed', workbookUploadFailed: 'Workbook upload failed',
  },
  kk: {
    overview: 'Шолу', editor: 'Деректер редакторы', imports: 'Деректерді жүктеу', anomalies: 'Аномалиялар', settings: 'Баптаулар',
    controlRoom: 'БАСҚАРУ ОРТАЛЫҒЫ', engineOnline: 'Қозғалтқыш жұмыс істеп тұр', version: 'v1.2 · ekt.kz + аномалиялар', purchasingEyebrow: 'САТЫП АЛУ / ҚОЙМАНЫ БАСҚАРУ', overviewTitle: 'Толықтыру кабинасы', liveData: '● Жанды деректер · {date}', syntheticDemo: '↻ Синтетикалық демо', ektDataset: '⚡️ ekt.kz деректері (Қазақстан)', anomaliesStress: '💥 Аномалиялар (стресс-тест)',
    needReplenishment: 'Толықтыру қажет', skuWarehousePairs: 'SKU / қойма жұптары', criticalRisk: 'Сыни тәуекел', stockoutBeforeArrival: 'келгенге дейінгі тапшылық', unitsToOrder: 'Тапсырыс бірліктері', afterPackageRounding: 'қаптама есебімен', orderBudget: 'Тапсырыс бюджеті', estimatedProcurementCost: 'сатып алудың болжамды құны', suppliersInvolved: 'Жеткізушілер', readyToReview: 'тексеруге дайын', anomaliesRemoved: 'Аномалиялар алынды', preservedForAudit: 'аудит үшін сақталды', lostDemandAdded: 'Жоғалған сұраныс', stockoutCorrection: 'тапшылық түзетуі', whatShouldWeOrder: 'Қазір неге тапсырыс', rightNow: 'беру керек?', recommendationsIntro: 'Ұсынымдар сұранысты, қорды, жолдағы тауарларды және жеткізуші шектеулерін ескереді — әр санның түсіндірмесі бар.', actionQueue: 'ӘРЕКЕТТЕР КЕЗЕГІ', recommendedOrders: 'Ұсынылған тапсырыстар', searchSku: 'SKU немесе тауарды іздеу…', allWarehouses: 'Барлық қоймалар', allSuppliers: 'Барлық жеткізушілер', allCategories: 'Барлық санаттар', allUrgency: 'Барлық жеделдік', sortByUrgency: 'Жеделдігі бойынша', largestOrder: 'Ең үлкен тапсырыс', lowestCover: 'Ең аз жабу', noRecommendations: 'Бұл сүзгілерге сай ұсыным жоқ.', urgency: 'Жеделдік', skuProduct: 'SKU / тауар', supplier: 'Жеткізуші', stockPosition: 'Қор жағдайы', demandLeadTime: 'Сұраныс / мерзім', orderBudgetColumn: 'Тапсырыс және бюджет', cover: 'Жабу', action: 'Әрекет', currentStock: 'ағымдағы қор', inTransit: 'жолда', dayLead: 'күн жеткізу', orderStatus: 'мәртебе', groupedBySupplier: 'Жеткізуші бойынша топтау', reviewBeforeApproval: 'Бекітпес бұрын тексеріңіз', supplierSku: '{count} SKU · мерзімі {days} күн', leadTime: 'Жеткізу мерзімі', stockIncoming: 'Қор + жолда', trend: 'Тренд', recentDailyDemand: 'Соңғы күндік сұраныс', demandVolatility: 'Сұраныс құбылмалылығы', seasonality: 'Маусымдылық', detected: 'Анықталды', notDetected: 'Анықталмады', auditAdjustments: 'Аудит түзетулері', anomaliesLostDemand: '{anomalies} аномалия · {demand} жоғалған сұраныс', demandSignal: 'Сұраныс сигналы', weeklyAverages: 'апталық орташа · соңғы 90 күн + болжам', actual: 'нақты', adjusted: 'түзетілген', forecast: 'болжам', stockout: 'тапшылық', anomaly: 'аномалия', calculationTrace: 'ЕСЕПТЕУ', forecastDuringLeadTime: 'Жеткізу мерзіміндегі болжам', safetyStock: '+ Қауіпсіздік қоры', currentStockIncoming: '− Ағымдағы қор / жолда', recommendedQuantity: 'Ұсынылған мөлшер', whyThisNumber: 'Бұл сан неге?', finalQuantity: 'Соңғы мөлшер', saveAdjustment: 'Түзетуді сақтау', approved: '✓ Бекітілді', approveOrder: 'Тапсырысты бекіту', approvalRequired: 'Жеткізуші әрекетінен бұрын бекіту қажет.',
    dataFoundation: 'ДЕРЕКТЕР НЕГІЗІ', bringSignals: 'Сигналдарды біріктіріңіз.', uploadDescription: 'Таза операциялық деректерді немесе толық ekt.kz Excel файлын жүктеңіз. Орыс және ағылшын тақырыптары қолданылады.', loadSynthetic: 'Синтетикалық демоны жүктеу', loadEkt: 'ekt.kz деректерін жүктеу (ТОО «Электрокомплект»)', loadExtreme: 'Экстремалды аномалиялар датасетін жүктеу', uploadWorkbook: 'Толық ekt.kz Excel файлын жүктеу (5 парақ)', uploadWorkbookHint: 'Сатуды, қорды, жолдағы тауарларды, жеткізушілерді және тапшылықтарды автоматты таниды', browseFile: 'Файлды сүйреңіз немесе таңдаңыз', salesHistory: 'Сату тарихы', currentStockImport: 'Ағымдағы қор', goodsInTransit: 'Жолдағы тауарлар', stockoutWindows: 'Тапшылық кезеңдері', supplierCatalog: 'Жеткізушілер каталогы', dailyTransactions: 'күнделікті операциялар · CSV / XLSX', inventoryByWarehouse: 'қоймадағы SKU қоры', expectedArrivals: 'күтілетін жеткізілімдер', lostDemandCorrection: 'жоғалған сұранысты түзету', leadMoqPackage: 'мерзім · MOQ · қаптама', safeOperations: 'Қауіпсіз жұмысқа арналған', privacyDescription: 'Клиент ID тек анонимді сілтеме ретінде қолданылады. PII қажет емес, тапсырыс автоматты жіберілмейді.',
    auditTrail: 'АУДИТ ЖУРНАЛЫ', detectedAnomalies: 'Анықталған аномалиялар', excludedExplanation: 'Бір реттік ірі операциялар әдеттегі сұраныстан алынады, бірақ жойылмайды.', date: 'Күн', skuWarehouse: 'SKU / қойма', customer: 'Клиент', quantity: 'Мөлшер', typical: 'Әдеттегі', forecastUse: 'Болжамда', reason: 'Себеп', included: 'Қосылған', excluded: 'Алынған', noAnomalies: 'Аномалия әзірге жоқ. Аудит журналын толтыру үшін демоны іске қосыңыз.',
    dataWorkspace: 'ДЕРЕКТЕР ЖҰМЫС АЙМАҒЫ', dataEditorTitle: 'Деректер редакторы', dataEditorDescription: 'Тауарларды, жеткізушілерді және операцияларды StockPilot ішінде жасаңыз. Черновик автоматты сақталады.', draftRestored: '↩ Черновик қалпына келтірілді', savedToSqlite: '● Деректер SQLite-ке сақталады', records: 'Жазбалар', find: 'Іздеу…', newRow: '＋ Жаңа жол', actions: 'Әрекеттер', edit: 'Өзгерту', delete: 'Жою', noRecords: 'Жазба жоқ. Бірінші жолды жасаңыз.', recordsCount: '{from}–{to} / {total}', zeroRecords: '0 жазба', newRecord: 'ЖАҢА ЖАЗБА', editRecord: 'ЖАЗБАНЫ ӨЗГЕРТУ', addRow: 'Жол қосу', editRow: 'Жолды өзгерту', saveRow: 'Жолды сақтау', saveChanges: 'Өзгерістерді сақтау', saving: 'Сақталуда…', editorHint: 'Пішіннің соңғы күйі бірнеше секунд сайын черновик ретінде автоматты сақталады.', required: 'міндетті', yes: 'Иә', no: 'Жоқ', products: 'Тауарлар', productsDescription: 'Сату және толықтыруға арналған SKU анықтамалығы', sales: 'Сатылымдар', salesDescription: 'Күнделікті нақты сатылымдар', stock: 'Қорлар', stockDescription: 'Қоймалардағы ағымдағы қор', transit: 'Жолда', transitDescription: 'Күтілетін жеткізілімдер', stockouts: 'Тапшылықтар', stockoutsDescription: 'Қор нөл болған кезеңдер', suppliers: 'Жеткізушілер', suppliersDescription: 'Жеткізу мерзімі, MOQ және қаптама', productName: 'Тауар атауы', category: 'Санат', price: 'Баға', active: 'Белсенді', customerId: 'Клиент', warehouse: 'Қойма', start: 'Басталуы', end: 'Аяқталуы', arrivalDate: 'Жеткізу күні', supplierId: 'Жеткізуші ID', supplierName: 'Жеткізуші', leadTimeDays: 'Жеткізу мерзімі, күн', moq: 'MOQ', packageSize: 'Қаптама', purchasePrice: 'Сатып алу бағасы', minimumOrderValue: 'Тапсырыстың мин. сомасы',
    settingsTitle: 'Баптаулар', settingsDescription: 'StockPilot-ты жұмыс үрдісіңізге бейімдеңіз. Өзгерістер осы құрылғыда сақталады.', generalSettings: 'Негізгі баптаулар', language: 'Интерфейс тілі', languageDescription: 'Қолданбаның барлық элементтеріне тіл таңдаңыз.', dateFormat: 'Күн форматы', dateFormatDescription: 'Өзіңізге ыңғайлы күн көрінісін таңдаңыз.', localDate: 'Жергілікті формат', isoDate: 'ISO (2026-09-23)', numberFormat: 'Сандар форматы', numberFormatDescription: 'Жергілікті бөлгіштер немесе қарапайым формат.', localeNumbers: 'Жергілікті', plainNumbers: 'Бөлгішсіз', compactMode: 'Ықшам кестелер', compactModeDescription: 'Көбірек жол көрсету үшін кесте аралықтарын азайту.', autoOpenDraft: 'Черновикті автоматты ашу', autoOpenDraftDescription: 'Кіруден кейін аяқталмаған редактор жазбасын бірден ашу.', resetSettings: 'Баптауларды қалпына келтіру', settingsSaved: 'Баптаулар сақталды', settingsReset: 'Баптаулар қалпына келтірілді', languageRussian: 'Русский', languageEnglish: 'English', languageKazakh: 'Қазақша',
    demoLoaded: 'Демо сценарийі жүктеліп, қайта есептелді', ektLoaded: '⚡️ ТОО «Электрокомплект» деректері жүктеліп, есептелді!', anomaliesLoaded: '💥 Аномалиялар датасеті жүктелді! {outliers} аномалия анықталды, {recommendations} тапсырыс есептелді!', couldNotLoad: 'Деректерді жүктеу мүмкін болмады', couldNotLoadRecommendations: 'Ұсынымдарды жүктеу мүмкін болмады', analyticsError: 'SKU аналитикасын жүктеу мүмкін болмады', orderApproved: 'Тапсырыс бекітілді', quantityAdjusted: 'Мөлшер түзетілді', workbookLoaded: 'Excel файлы жүктелді: {count} ұсыным есептелді', demoDatasetLoaded: 'Демо датасеті жүктелді', draftUnavailable: 'Черновик әзірге қолжетімсіз', changesSaved: 'Өзгерістер сақталды, ұсынымдар қайта есептелді', couldNotSave: 'Жолды сақтау мүмкін болмады', rowDeleted: 'Жол жойылды', couldNotDelete: 'Жолды жою мүмкін болмады', confirmDelete: 'Бұл жол жойылсын ба?', uploadFailed: 'Жүктеу сәтсіз аяқталды', workbookUploadFailed: 'Excel файлын жүктеу сәтсіз аяқталды',
  },
}

const supplementalTranslations: Record<Locale, Record<string, string>> = {
  ru: { discardChanges: 'Отменить несохранённые изменения?', chartRange: 'Период графика', dayRange: 'День', weekRange: 'Неделя', threeMonths: '3 мес.', nineMonths: '9 мес.', sidebarHide: 'Скрыть боковую панель', sidebarShow: 'Показать боковую панель', brandSubtitle: 'управление запасами' },
  en: { discardChanges: 'Discard unsaved changes?', chartRange: 'Chart range', dayRange: 'Day', weekRange: 'Week', threeMonths: '3 months', nineMonths: '9 months', sidebarHide: 'Hide sidebar', sidebarShow: 'Show sidebar', brandSubtitle: 'inventory control' },
  kk: { discardChanges: 'Сақталмаған өзгерістер жойылсын ба?', chartRange: 'График кезеңі', dayRange: 'Күн', weekRange: 'Апта', threeMonths: '3 ай', nineMonths: '9 ай', sidebarHide: 'Бүйірлік панельді жасыру', sidebarShow: 'Бүйірлік панельді көрсету', brandSubtitle: 'қорларды басқару' },
}

function readLocale(): Locale {
  const value = window.localStorage.getItem(LOCALE_STORAGE_KEY)
  return value === 'en' || value === 'kk' ? value : 'ru'
}

function readSettings(): UserSettings {
  try {
    const parsed = JSON.parse(window.localStorage.getItem(SETTINGS_STORAGE_KEY) || '{}') as Partial<UserSettings>
    return { ...defaultSettings, ...parsed }
  } catch {
    return defaultSettings
  }
}

let activeLocale: Locale = readLocale()
let activeSettings: UserSettings = readSettings()

const localeTag = (locale: Locale) => locale === 'kk' ? 'kk-KZ' : locale === 'en' ? 'en-US' : 'ru-RU'

export function formatNumber(value: number, locale: Locale = activeLocale, mode: NumberFormat = activeSettings.numberFormat): string {
  return new Intl.NumberFormat(mode === 'plain' ? 'en-US' : localeTag(locale), { maximumFractionDigits: 2, useGrouping: mode !== 'plain' }).format(value)
}

export function formatDate(value: Date | string, locale: Locale = readLocale(), mode: DateFormat = readSettings().dateFormat): string {
  const date = value instanceof Date ? value : new Date(value)
  if (mode === 'iso') return date.toISOString().slice(0, 10)
  return new Intl.DateTimeFormat(localeTag(locale), { month: 'short', day: 'numeric', year: 'numeric' }).format(date)
}

interface I18nContextValue {
  locale: Locale
  setLocale: (locale: Locale) => void
  settings: UserSettings
  updateSettings: (patch: Partial<UserSettings>) => void
  resetSettings: () => void
  t: (key: string, values?: Record<string, string | number>) => string
  formatNumber: (value: number) => string
  formatDate: (value: Date | string) => string
}

const I18nContext = createContext<I18nContextValue | null>(null)

export function I18nProvider({ children }: { children: ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>(readLocale)
  const [settings, setSettings] = useState<UserSettings>(readSettings)
  activeLocale = locale
  activeSettings = settings

  useEffect(() => {
    window.localStorage.setItem(LOCALE_STORAGE_KEY, locale)
    document.documentElement.lang = locale === 'kk' ? 'kk' : locale
  }, [locale])

  useEffect(() => {
    window.localStorage.setItem(SETTINGS_STORAGE_KEY, JSON.stringify(settings))
    document.body.classList.toggle('compact-mode', settings.compactMode)
  }, [settings])

  const value = useMemo<I18nContextValue>(() => ({
    locale,
    setLocale: (next: Locale) => setLocaleState(next),
    settings,
    updateSettings: patch => setSettings(current => ({ ...current, ...patch })),
    resetSettings: () => setSettings(defaultSettings),
    t: (key, values) => {
      let message = translations[locale][key] || supplementalTranslations[locale][key] || translations.en[key] || supplementalTranslations.en[key] || key
      for (const [name, replacement] of Object.entries(values || {})) message = message.replace(new RegExp(`\\{${name}\\}`, 'g'), String(replacement))
      return message.replace(/[⚡️💥✦📑↻]/gu, '').replace(/StockPilot/g, 'basqar').replace(/\s{2,}/g, ' ').trim()
    },
    formatNumber: value => formatNumber(value, locale, settings.numberFormat),
    formatDate: value => formatDate(value, locale, settings.dateFormat),
  }), [locale, settings])

  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>
}

export function useI18n(): I18nContextValue {
  const context = useContext(I18nContext)
  if (!context) throw new Error('useI18n must be used inside I18nProvider')
  return context
}

// New dashboard copy uses the same locale as the existing translation provider.
const dashboardCopy: Record<string, [string, string]> = {
  'План закупок': ['Purchase plan', 'Сатып алу жоспары'], 'Данные': ['Data', 'Деректер'], 'Исключения': ['Exceptions', 'Ерекшеліктер'], 'История': ['History', 'Тарих'], 'Политики': ['Policies', 'Саясаттар'],
  'К закупке': ['To purchase', 'Сатып алу'], 'Критические': ['Critical', 'Өте маңызды'], 'Бюджет': ['Budget', 'Бюджет'], 'Рекомендации': ['Recommendations', 'Ұсынымдар'],
  'Пересчитать': ['Recalculate', 'Қайта есептеу'], 'Экспорт': ['Export', 'Экспорт'], 'По позициям': ['By item', 'Тауар бойынша'], 'По поставщикам': ['By supplier', 'Жеткізуші бойынша'],
  'Поиск по названию или SKU': ['Search name or SKU', 'Атауы немесе SKU бойынша іздеу'], 'Фильтры': ['Filters', 'Сүзгілер'], 'Сбросить': ['Reset', 'Қалпына келтіру'],
  'Приоритет': ['Priority', 'Басымдық'], 'Статус': ['Status', 'Мәртебе'], 'Сортировка': ['Sort order', 'Сұрыптау'], 'Все приоритеты': ['All priorities', 'Барлық басымдықтар'], 'Все статусы': ['All statuses', 'Барлық мәртебелер'],
  'Критический': ['Critical', 'Өте маңызды'], 'Высокий': ['High', 'Жоғары'], 'Средний': ['Medium', 'Орташа'], 'Плановый': ['Planned', 'Жоспарлы'], 'Черновик': ['Draft', 'Жоба'], 'Изменено': ['Adjusted', 'Өзгертілген'], 'Утверждено': ['Approved', 'Бекітілген'],
  'Назад': ['Previous', 'Артқа'], 'Далее': ['Next', 'Келесі'], 'Закрыть': ['Close', 'Жабу'], 'Сохранить': ['Save', 'Сақтау'], 'Утвердить': ['Approve', 'Бекіту'], 'К заказу': ['Order quantity', 'Тапсырыс саны'], 'Стоимость': ['Cost', 'Құны'],
  'Позиция / SKU': ['Item / SKU', 'Тауар / SKU'], 'Загрузка файлов': ['File upload', 'Файл жүктеу'], 'Закуп': ['Purchase', 'Сатып алу'], 'Продажа': ['Sale', 'Сату'], 'Движения товаров': ['Stock movements', 'Тауар қозғалысы'], 'Справочники': ['Reference data', 'Анықтамалықтар'],
  'Поступление': ['Receipt', 'Кіріс'], 'Перемещение': ['Transfer', 'Ауыстыру'], 'Корректировка': ['Adjustment', 'Түзету'], 'Возврат': ['Return', 'Қайтару'], 'Журнал': ['Journal', 'Журнал'], 'Управление товарами': ['Inventory management', 'Тауарларды басқару'],
  'Разделы товарного учёта': ['Inventory sections', 'Тауар есебі бөлімдері'], 'Цена за единицу, ₸ *': ['Unit price, ₸ *', 'Бірлік бағасы, ₸ *'], 'Введите цену': ['Enter a price', 'Бағаны енгізіңіз'], 'поз.': ['items', 'позиция'],
  'Управление закупками': ['Procurement management', 'Сатып алуды басқару'], 'Карточка позиции': ['Item details', 'Тауар туралы'], 'График спроса': ['Demand chart', 'Сұраныс графигі'], 'Причина изменения': ['Adjustment reason', 'Өзгерту себебі'],
  'Центральный склад': ['Central warehouse', 'Орталық қойма'], 'Северный склад': ['North warehouse', 'Солтүстік қойма'], 'Южный склад': ['South warehouse', 'Оңтүстік қойма'],
}
export function translateText(text: string): string {
  if (activeLocale === 'ru') return text
  const custom = dashboardCopy[text]
  if (custom) return custom[activeLocale === 'en' ? 0 : 1]
  const key = Object.keys(translations.ru).find(key => translations.ru[key] === text)
  return key ? translations[activeLocale][key] || text : text
}
